export const BATANGAS_LOCATIONS = [
  { name: 'Batangas City', type: 'city', coordinates: { latitude: 13.7565, longitude: 121.0583 }, barangays: ['Alangilan', 'Balagtas', 'Kumintang Ibaba'] },
  { name: 'Lipa City', type: 'city', coordinates: { latitude: 13.9411, longitude: 121.1622 }, barangays: ['Plaridel', 'Marawoy', 'Sabang'] },
  { name: 'Santo Tomas City', type: 'city', coordinates: { latitude: 14.1078, longitude: 121.1414 }, barangays: ['San Bartolome', 'Santiago', 'San Pedro'] },
  { name: 'Tanauan City', type: 'city', coordinates: { latitude: 14.0869, longitude: 121.1498 }, barangays: ['Altura Bata', 'Darasa', 'Janopol Oriental'] },

  { name: 'Agoncillo', type: 'municipality', coordinates: { latitude: 13.9336, longitude: 120.9325 }, barangays: ['Bangin', 'Banyaga', 'Poblacion'] },
  { name: 'Alitagtag', type: 'municipality', coordinates: { latitude: 13.8648, longitude: 121.0008 }, barangays: ['Concepcion', 'Munlawin', 'Ping-as'] },
  { name: 'Balayan', type: 'municipality', coordinates: { latitude: 13.9371, longitude: 120.7296 }, barangays: ['Calan', 'Poblacion', 'Sampaga'] },
  { name: 'Balete', type: 'municipality', coordinates: { latitude: 14.0333, longitude: 121.1000 }, barangays: ['Alangilan', 'Magapi', 'Poblacion'] },
  { name: 'Bauan', type: 'municipality', coordinates: { latitude: 13.7917, longitude: 121.0083 }, barangays: ['Manghinao', 'Poblacion 1', 'Sampaguita'] },
  { name: 'Calaca', type: 'municipality', coordinates: { latitude: 13.9333, longitude: 120.8167 }, barangays: ['Coral ni Lopez', 'Dacanlao', 'Matipok'] },
  { name: 'Calatagan', type: 'municipality', coordinates: { latitude: 13.8333, longitude: 120.6333 }, barangays: ['Bagong Silang', 'Baha', 'Poblacion 1'] },
  { name: 'Cuenca', type: 'municipality', coordinates: { latitude: 13.9000, longitude: 121.0500 }, barangays: ['Balagbag', 'Don Juan', 'Poblacion 1'] },
  { name: 'Ibaan', type: 'municipality', coordinates: { latitude: 13.8167, longitude: 121.1333 }, barangays: ['Calamias', 'Lapu-lapu', 'Poblacion'] },
  { name: 'Laurel', type: 'municipality', coordinates: { latitude: 14.0500, longitude: 120.9167 }, barangays: ['Asisan', 'Balakilong', 'Niyugan'] },
  { name: 'Lemery', type: 'municipality', coordinates: { latitude: 13.8792, longitude: 120.9139 }, barangays: ['Bagong Pook', 'Matingain', 'Poblacion'] },
  { name: 'Lian', type: 'municipality', coordinates: { latitude: 14.0333, longitude: 120.6500 }, barangays: ['Binubusan', 'Lumaniag', 'Poblacion'] },
  { name: 'Lobo', type: 'municipality', coordinates: { latitude: 13.6500, longitude: 121.2167 }, barangays: ['Apar', 'Balatbat', 'Poblacion'] },
  { name: 'Mabini', type: 'municipality', coordinates: { latitude: 13.7500, longitude: 120.9333 }, barangays: ['Anilao Proper', 'Bagalangit', 'Mainaga'] },
  { name: 'Malvar', type: 'municipality', coordinates: { latitude: 14.0447, longitude: 121.1589 }, barangays: ['Luta Norte', 'Poblacion', 'San Andres'] },
  { name: 'Mataasnakahoy', type: 'municipality', coordinates: { latitude: 13.9500, longitude: 121.1167 }, barangays: ['Bayorbor', 'Kinalaglagan', 'Poblacion 2'] },
  { name: 'Nasugbu', type: 'municipality', coordinates: { latitude: 14.0667, longitude: 120.6333 }, barangays: ['Balaytigui', 'Bucana', 'Wawa'] },
  { name: 'Padre Garcia', type: 'municipality', coordinates: { latitude: 13.8833, longitude: 121.2167 }, barangays: ['Banaba', 'Castillo', 'Poblacion'] },
  { name: 'Rosario', type: 'municipality', coordinates: { latitude: 13.8500, longitude: 121.2000 }, barangays: ['Alupay', 'Leviste', 'Natu'] },
  { name: 'San Jose', type: 'municipality', coordinates: { latitude: 13.8833, longitude: 121.1167 }, barangays: ['Aguila', 'Anus', 'Banaybanay'] },
  { name: 'San Juan', type: 'municipality', coordinates: { latitude: 13.8167, longitude: 121.4000 }, barangays: ['Abung', 'Calicanto', 'Poblacion'] },
  { name: 'San Luis', type: 'municipality', coordinates: { latitude: 13.8500, longitude: 121.3833 }, barangays: ['Balite', 'Luya', 'Poblacion'] },
  { name: 'San Nicolas', type: 'municipality', coordinates: { latitude: 13.9333, longitude: 120.9500 }, barangays: ['Abelo', 'Bancoro', 'Poblacion'] },
  { name: 'San Pascual', type: 'municipality', coordinates: { latitude: 13.8167, longitude: 121.0167 }, barangays: ['Alalum', 'Poblacion', 'Sambat'] },
  { name: 'Santa Teresita', type: 'municipality', coordinates: { latitude: 13.8667, longitude: 121.2167 }, barangays: ['Antipolo', 'Bihis', 'Poblacion'] },
  { name: 'Taal', type: 'municipality', coordinates: { latitude: 13.8833, longitude: 120.9167 }, barangays: ['Baliang', 'Cawit', 'Poblacion 1'] },
  { name: 'Talisay', type: 'municipality', coordinates: { latitude: 14.1000, longitude: 121.0167 }, barangays: ['Aya', 'Buco', 'Poblacion 1'] },
  { name: 'Taysan', type: 'municipality', coordinates: { latitude: 13.8667, longitude: 121.1000 }, barangays: ['Bilogo', 'Poblacion East', 'Sampaga'] },
  { name: 'Tingloy', type: 'municipality', coordinates: { latitude: 13.6667, longitude: 120.8667 }, barangays: ['Calumpang', 'Mabini', 'Poblacion'] },
  { name: 'Tuy', type: 'municipality', coordinates: { latitude: 14.0167, longitude: 120.7333 }, barangays: ['Acle', 'Bolbok', 'Luna'] },
];

export const BATANGAS_LOCATION_OPTIONS = BATANGAS_LOCATIONS.map((loc) => ({
  key: loc.name.toLowerCase().replace(/[^a-z0-9]+/g, '_'),
  label: loc.name,
  type: loc.type,
  coordinates: loc.coordinates,
  barangays: loc.barangays,
}));

