// Official Batangas LGU and barangay options sourced from PSGC data.
export const BATANGAS_LOCATIONS = [
  {
    name: 'Agoncillo',
    type: 'municipality',
    coordinates: { latitude: 13.9336, longitude: 120.9325 },
    barangays: [
      'Bagong Sikat',
      'Balangon',
      'Bangin',
      'Banyaga',
      'Barigon',
      'Bilibinwang',
      'Coral Na Munti',
      'Guitna',
      'Pamiga',
      'Panhulan',
      'Pansipit',
      'Poblacion',
      'Pook',
      'San Jacinto',
      'San Teodoro',
      'Santa Cruz',
      'Santo Tomas',
      'Subic Ibaba',
      'Subic Ilaya',
    ],
  },
  {
    name: 'Alitagtag',
    type: 'municipality',
    coordinates: { latitude: 13.8648, longitude: 121.0008 },
    barangays: [
      'Balagbag',
      'Concordia',
      'Dalipit East',
      'Dalipit West',
      'Dominador East',
      'Dominador West',
      'Munlawin Norte',
      'Munlawin Sur',
      'Muzon Primero',
      'Muzon Segundo',
      'Pinagkurusan',
      'Ping-As',
      'Poblacion East',
      'Poblacion West',
      'San Jose',
      'San Juan',
      'Santa Cruz',
    ],
  },
  {
    name: 'Balayan',
    type: 'municipality',
    coordinates: { latitude: 13.9371, longitude: 120.7296 },
    barangays: [
      'Baclaran',
      'Barangay 10 (Pob.)',
      'Barangay 11 (Pob.)',
      'Barangay 12 (Pob.)',
      'Barangay 2 (Pob.)',
      'Barangay 3 (Pob.)',
      'Barangay 4 (Pob.)',
      'Barangay 5 (Pob.)',
      'Barangay 6 (Pob.)',
      'Barangay 7 (Pob.)',
      'Barangay 8 (Pob.)',
      'Barangay 9 (Pob.)',
      'Calan',
      'Caloocan',
      'Calzada',
      'Canda',
      'Carenahan',
      'Caybunga',
      'Cayponce',
      'Dalig',
      'Dao',
      'Dilao',
      'Duhatan',
      'Durungao',
      'Gimalas',
      'Gumamela',
      'Lanatan',
      'Langgangan',
      'Lucban Pook',
      'Lucban Putol',
      'Magabe',
      'Malalay',
      'Munting Tubig',
      'Navotas',
      'Palikpikan',
      'Patugo',
      'Pooc',
      'Sambat',
      'Sampaga',
      'San Juan',
      'San Piro',
      'Santol',
      'Sukol',
      'Tactac',
      'Taludtud',
      'Tanggoy',
    ],
  },
  {
    name: 'Balete',
    type: 'municipality',
    coordinates: { latitude: 14.0333, longitude: 121.1 },
    barangays: [
      'Alangilan',
      'Calawit',
      'Looc',
      'Makina',
      'Malabanan',
      'Paligawan',
      'Palsara',
      'Poblacion',
      'Sala',
      'Sampalocan',
      'San Sebastian',
      'Solis',
    ],
  },
  {
    name: 'Batangas City',
    type: 'city',
    coordinates: { latitude: 13.7565, longitude: 121.0583 },
    barangays: [
      'Alangilan',
      'Balagtas',
      'Balete',
      'Banaba Center',
      'Banaba Ibaba',
      'Banaba Kanluran',
      'Banaba Silangan',
      'Barangay 1 (Pob.)',
      'Barangay 10 (Pob.)',
      'Barangay 11 (Pob.)',
      'Barangay 12 (Pob.)',
      'Barangay 13 (Pob.)',
      'Barangay 14 (Pob.)',
      'Barangay 15 (Pob.)',
      'Barangay 16 (Pob.)',
      'Barangay 17 (Pob.)',
      'Barangay 18 (Pob.)',
      'Barangay 19 (Pob.)',
      'Barangay 2 (Pob.)',
      'Barangay 20 (Pob.)',
      'Barangay 21 (Pob.)',
      'Barangay 22 (Pob.)',
      'Barangay 23 (Pob.)',
      'Barangay 24 (Pob.)',
      'Barangay 3 (Pob.)',
      'Barangay 4 (Pob.)',
      'Barangay 5 (Pob.)',
      'Barangay 6 (Pob.)',
      'Barangay 7 (Pob.)',
      'Barangay 8 (Pob.)',
      'Barangay 9 (Pob.)',
      'Bilogo',
      'Bolbok',
      'Bukal',
      'Calicanto',
      'Catandala',
      'Concepcion',
      'Conde Itaas',
      'Conde Labak',
      'Cuta',
      'Dalig',
      'Dela Paz',
      'Dela Paz Pulot Aplaya',
      'Dela Paz Pulot Itaas',
      'Domoclay',
      'Dumantay',
      'Gulod Itaas',
      'Gulod Labak',
      'Haligue Kanluran',
      'Haligue Silangan',
      'Ilihan',
      'Kumba',
      'Kumintang Ibaba',
      'Kumintang Ilaya',
      'Libjo',
      'Liponpon, Isla Verde',
      'Maapas',
      'Mabacong',
      'Mahabang Dahilig',
      'Mahabang Parang',
      'Mahacot Silangan',
      'Malalim',
      'Malibayo',
      'Malitam',
      'Maruclap',
      'Pagkilatan',
      'Paharang Kanluran',
      'Paharang Silangan',
      'Pallocan Kanluran',
      'Pinamucan',
      'Pinamucan Ibaba',
      'Pinamucan Silangan',
      'Sampaga',
      'San Agapito, Isla Verde',
      'San Agustin Kanluran, Isla Verde',
      'San Agustin Silangan, Isla Verde',
      'San Andres, Isla Verde',
      'San Antonio, Isla Verde',
      'San Isidro',
      'San Jose Sico',
      'San Miguel',
      'San Pedro',
      'Santa Clara',
      'Santa Rita Aplaya',
      'Santa Rita Karsada',
      'Santo Domingo',
      'Simlong',
      'Sirang Lupa',
      'Sorosoro Ibaba',
      'Sorosoro Ilaya',
      'Sorosoro Karsada',
      'Tabangao Ambulong',
      'Tabangao Aplaya',
      'Tabangao Dao',
      'Talahib Pandayan',
      'Talahib Payapa',
      'Talumpok Kanluran',
      'Talumpok Silangan',
      'Tinga Itaas',
      'Tinga Labak',
      'Tulo',
      'Wawa',
    ],
  },
  {
    name: 'Bauan',
    type: 'municipality',
    coordinates: { latitude: 13.7917, longitude: 121.0083 },
    barangays: [
      'Alagao',
      'Aplaya',
      'As-Is',
      'Bagong Silang',
      'Baguilawa',
      'Barangay I (Pob.)',
      'Barangay II (Pob.)',
      'Barangay III (Pob.)',
      'Barangay IV (Pob.)',
      'Bolo',
      'Colvo',
      'Cupang',
      'Durungao',
      'Gulibay',
      'Inicbulan',
      'Locloc',
      'Magalang-Galang',
      'Malindig',
      'Manalupong',
      'Manghinao Proper',
      'Manghinao Uno',
      'New Danglayan',
      'Orense',
      'Pitugo',
      'Rizal',
      'Sampaguita',
      'San Agustin',
      'San Andres Proper',
      'San Andres Uno',
      'San Diego',
      'San Miguel',
      'San Pablo',
      'San Pedro',
      'San Roque',
      'San Teodoro',
      'San Vicente',
      'Santo Domingo',
      'Sinala',
    ],
  },
  {
    name: 'Calaca',
    type: 'municipality',
    coordinates: { latitude: 13.9333, longitude: 120.8167 },
    barangays: [
      'Baclas',
      'Bagong Tubig',
      'Balimbing',
      'Bambang',
      'Barangay 1 (Pob.)',
      'Barangay 3 (Pob.)',
      'Barangay 4 (Pob.)',
      'Barangay 5 (Pob.)',
      'Barangay 6 (Pob.)',
      'Bisaya',
      'Cahil',
      'Calantas',
      'Caluangan',
      'Camastilisan',
      'Coral Ni Bacal',
      'Coral Ni Lopez',
      'Dacanlao',
      'Dila',
      'Loma',
      'Lumbang Calzada',
      'Lumbang Na Bata',
      'Lumbang Na Matanda',
      'Madalunot',
      'Makina',
      'Matipok',
      'Munting Coral',
      'Niyugan',
      'Pantay',
      'Puting Bato East',
      'Puting Bato West',
      'Puting Kahoy',
      'Quisumbing',
      'Salong',
      'San Rafael',
      'Sinisian',
      'Talisay',
      'Tamayo',
      'Timbain',
    ],
  },
  {
    name: 'Calatagan',
    type: 'municipality',
    coordinates: { latitude: 13.8333, longitude: 120.6333 },
    barangays: [
      'Bagong Silang',
      'Baha',
      'Balibago',
      'Balitoc',
      'Barangay 1 (Pob.)',
      'Barangay 2 (Pob.)',
      'Barangay 3 (Pob.)',
      'Barangay 4 (Pob.)',
      'Biga',
      'Bucal',
      'Carlosa',
      'Encarnacion',
      'Gulod',
      'Hukay',
      'Lucsuhin',
      'Luya',
      'Paraiso',
      'Quilitisan',
      'Real',
      'Sambungan',
      'Santa Ana',
      'Talibayog',
      'Talisay',
      'Tanagan',
    ],
  },
  {
    name: 'Cuenca',
    type: 'municipality',
    coordinates: { latitude: 13.9, longitude: 121.05 },
    barangays: [
      'Balagbag',
      'Barangay 1 (Pob.)',
      'Barangay 2 (Pob.)',
      'Barangay 3 (Pob.)',
      'Barangay 4 (Pob.)',
      'Barangay 5 (Pob.)',
      'Barangay 6 (Pob.)',
      'Barangay 7 (Pob.)',
      'Barangay 8 (Pob.)',
      'Bungahan',
      'Calumayin',
      'Dalipit East',
      'Dalipit West',
      'Dita',
      'Don Juan',
      'Ibabao',
      'Labac',
      'Pinagkaisahan',
      'San Felipe',
      'San Isidro',
    ],
  },
  {
    name: 'Ibaan',
    type: 'municipality',
    coordinates: { latitude: 13.8167, longitude: 121.1333 },
    barangays: [
      'Bago',
      'Balanga',
      'Bungahan',
      'Calamias',
      'Catandala',
      'Coliat',
      'Dayapan',
      'Lapu-lapu',
      'Lucsuhin',
      'Malainin',
      'Matala',
      'Munting-Tubig',
      'Palindan',
      'Pangao',
      'Panghayaan',
      'Poblacion',
      'Quilo',
      'Sabang',
      'Salaban I',
      'Salaban II',
      'San Agustin',
      'Sandalan',
      'Santo Niño',
      'Talaibon',
      'Tulay Na Patpat',
    ],
  },
  {
    name: 'Laurel',
    type: 'municipality',
    coordinates: { latitude: 14.05, longitude: 120.9167 },
    barangays: [
      'As-Is',
      'Balakilong',
      'Barangay 1 (Pob.)',
      'Barangay 2 (Pob.)',
      'Barangay 3 (Pob.)',
      'Barangay 4 (Pob.)',
      'Barangay 5 (Pob.)',
      'Berinayan',
      'Bugaan East',
      'Bugaan West',
      'Buso-buso',
      'Dayap Itaas',
      'J. Leviste',
      'Molinete',
      'Niyugan',
      'Paliparan',
      'San Gabriel',
      'San Gregorio',
      'Santa Maria',
      'Ticub',
    ],
  },
  {
    name: 'Lemery',
    type: 'municipality',
    coordinates: { latitude: 13.8792, longitude: 120.9139 },
    barangays: [
      'Anak-Dagat',
      'Arumahan',
      'Ayao-iyao',
      'Bagong Pook',
      'Bagong Sikat',
      'Balanga',
      'Bukal',
      'Cahilan I',
      'Cahilan II',
      'Dayapan',
      'District I (Pob.)',
      'District II (Pob.)',
      'District III (Pob.)',
      'District IV (Pob.)',
      'Gulod',
      'Lucky',
      'Maguihan',
      'Mahabang Dahilig',
      'Mahayahay',
      'Maigsing Dahilig',
      'Maligaya',
      'Malinis',
      'Masalisi',
      'Mataas Na Bayan',
      'Matingain I',
      'Matingain II',
      'Mayasang',
      'Niugan',
      'Nonong Casto',
      'Palanas',
      'Payapa Ibaba',
      'Payapa Ilaya',
      'Rizal',
      'Sambal Ibaba',
      'Sambal Ilaya',
      'San Isidro Ibaba',
      'San Isidro Itaas',
      'Sinisian East',
      'Sinisian West',
      'Talaga',
      'Tubigan',
      'Tubuan',
      'Wawa Ibaba',
      'Wawa Ilaya',
    ],
  },
  {
    name: 'Lian',
    type: 'municipality',
    coordinates: { latitude: 14.0333, longitude: 120.65 },
    barangays: [
      'Bagong Pook',
      'Balibago',
      'Barangay 1 (Pob.)',
      'Barangay 2 (Pob.)',
      'Barangay 3 (Pob.)',
      'Barangay 4 (Pob.)',
      'Barangay 5 (Pob.)',
      'Binubusan',
      'Bungahan',
      'Cumba',
      'Humayingan',
      'Kapito',
      'Lumaniag',
      'Malaruhatan',
      'Matabungkay',
      'Prenza',
      'Puting-Kahoy',
      'San Diego',
    ],
  },
  {
    name: 'Lipa City',
    type: 'city',
    coordinates: { latitude: 13.9411, longitude: 121.1622 },
    barangays: [
      'Adya',
      'Anilao',
      'Anilao-Labac',
      'Antipolo Del Norte',
      'Antipolo Del Sur',
      'Bagong Pook',
      'Balintawak',
      'Banaybanay',
      'Barangay 12 (Pob.)',
      'Bolbok',
      'Bugtong na Pulo',
      'Bulacnin',
      'Calamias',
      'Cumba',
      'Dagatan',
      'Duhatan',
      'Halang',
      'Inosloban',
      'Kayumanggi',
      'Latag',
      'Lodlod',
      'Lumbang',
      'Mabini',
      'Malagonlong',
      'Malitlit',
      'Marauoy',
      'Mataas Na Lupa',
      'Munting Pulo',
      'Pagolingin Bata',
      'Pagolingin East',
      'Pagolingin West',
      'Pangao',
      'Pinagkawitan',
      'Pinagtongulan',
      'Plaridel',
      'Poblacion Barangay 1',
      'Poblacion Barangay 11',
      'Poblacion Barangay 2',
      'Poblacion Barangay 3',
      'Poblacion Barangay 4',
      'Poblacion Barangay 5',
      'Poblacion Barangay 6',
      'Poblacion Barangay 7',
      'Poblacion Barangay 8',
      'Poblacion Barangay 9',
      'Poblacion Barangay 9-A',
      'Pusil',
      'Quezon',
      'Rizal',
      'Sabang',
      'Sampaguita',
      'San Benito',
      'San Carlos',
      'San Celestino',
      'San Francisco',
      'San Guillermo',
      'San Jose',
      'San Lucas',
      'San Salvador',
      'San Sebastian',
      'Santo Niño',
      'Santo Toribio',
      'Sapac',
      'Sico',
      'Talisay',
      'Tambo',
      'Tangob',
      'Tanguay',
      'Tibig',
      'Tipacan',
    ],
  },
  {
    name: 'Lobo',
    type: 'municipality',
    coordinates: { latitude: 13.65, longitude: 121.2167 },
    barangays: [
      'Apar',
      'Balatbat',
      'Balibago',
      'Banalo',
      'Biga',
      'Bignay',
      'Calo',
      'Calumpit',
      'Fabrica',
      'Jaybanga',
      'Lagadlarin',
      'Mabilog Na Bundok',
      'Malabrigo',
      'Malalim Na Sanog',
      'Masaguitsit',
      'Nagtalongtong',
      'Nagtoctoc',
      'Olo-olo',
      'Pinaghawanan',
      'Poblacion',
      'San Miguel',
      'San Nicolas',
      'Sawang',
      'Soloc',
      'Tayuman',
    ],
  },
  {
    name: 'Mabini',
    type: 'municipality',
    coordinates: { latitude: 13.75, longitude: 120.9333 },
    barangays: [
      'Anilao East',
      'Anilao Proper',
      'Bagalangit',
      'Bulacan',
      'Calamias',
      'Estrella',
      'Gasang',
      'Laurel',
      'Ligaya',
      'Mainaga',
      'Mainit',
      'Majuben',
      'Malimatoc I',
      'Malimatoc II',
      'Pilahan',
      'Poblacion',
      'Pulang Lupa',
      'Pulong Anahao',
      'Pulong Balibaguhan',
      'Pulong Niogan',
      'Saguing',
      'Sampaguita',
      'San Francisco',
      'San Jose',
      'San Juan',
      'San Teodoro',
      'Santa Ana',
      'Santa Mesa',
      'Santo Niño',
      'Santo Tomas',
      'Solo',
      'Talaga East',
      'Talaga Proper',
    ],
  },
  {
    name: 'Malvar',
    type: 'municipality',
    coordinates: { latitude: 14.0447, longitude: 121.1589 },
    barangays: [
      'Bagong Pook',
      'Bilucao',
      'Bulihan',
      'Luta Del Norte',
      'Luta Del Sur',
      'Poblacion',
      'San Andres',
      'San Fernando',
      'San Gregorio',
      'San Isidro East',
      'San Juan',
      'San Pedro I',
      'San Pioquinto',
      'Santiago',
    ],
  },
  {
    name: 'Mataasnakahoy',
    type: 'municipality',
    coordinates: { latitude: 13.95, longitude: 121.1167 },
    barangays: [
      'Bayorbor',
      'Bubuyan',
      'Calingatan',
      'District I (Pob.)',
      'District II (Pob.)',
      'District III (Pob.)',
      'District IV (Pob.)',
      'Kinalaglagan',
      'Loob',
      'Lumang Lipa',
      'Manggahan',
      'Nangkaan',
      'San Sebastian',
      'Santol',
      'Upa',
    ],
  },
  {
    name: 'Nasugbu',
    type: 'municipality',
    coordinates: { latitude: 14.0667, longitude: 120.6333 },
    barangays: [
      'Aga',
      'Balaytigui',
      'Banilad',
      'Barangay 1 (Pob.)',
      'Barangay 10 (Pob.)',
      'Barangay 11 (Pob.)',
      'Barangay 12 (Pob.)',
      'Barangay 2 (Pob.)',
      'Barangay 3 (Pob.)',
      'Barangay 4 (Pob.)',
      'Barangay 5 (Pob.)',
      'Barangay 6 (Pob.)',
      'Barangay 7 (Pob.)',
      'Barangay 8 (Pob.)',
      'Barangay 9 (Pob.)',
      'Bilaran',
      'Bucana',
      'Bulihan',
      'Bunducan',
      'Calayo',
      'Catandaan',
      'Cogunan',
      'Dayap',
      'Kaylaway',
      'Kayrilaw',
      'Latag',
      'Looc',
      'Lumbangan',
      'Malapad Na Bato',
      'Mataas Na Pulo',
      'Maugat',
      'Munting Indan',
      'Natipuan',
      'Pantalan',
      'Putat',
      'Reparo',
      'Talangan',
      'Tumalim',
      'Utod',
      'Wawa',
    ],
  },
  {
    name: 'Padre Garcia',
    type: 'municipality',
    coordinates: { latitude: 13.8833, longitude: 121.2167 },
    barangays: [
      'Banaba',
      'Banaybanay',
      'Bawi',
      'Bukal',
      'Castillo',
      'Cawongan',
      'Manggas',
      'Maugat East',
      'Pansol',
      'Payapa',
      'Poblacion',
      'Quilo-quilo North',
      'Quilo-quilo South',
      'San Felipe',
      'San Miguel',
      'Tamak',
      'Tangob',
    ],
  },
  {
    name: 'Rosario',
    type: 'municipality',
    coordinates: { latitude: 13.85, longitude: 121.2 },
    barangays: [
      'Alupay',
      'Antipolo',
      'Bagong Pook',
      'Balibago',
      'Barangay A (Pob.)',
      'Barangay B (Pob.)',
      'Barangay C (Pob.)',
      'Barangay D (Pob.)',
      'Barangay E (Pob.)',
      'Bayawang',
      'Baybayin',
      'Bulihan',
      'Cahigam',
      'Calantas',
      'Colongan',
      'Itlugan',
      'Leviste',
      'Lumbangan',
      'Maalas-As',
      'Mabato',
      'Mabunga',
      'Macalamcam A',
      'Macalamcam B',
      'Malaya',
      'Maligaya',
      'Marilag',
      'Matamis',
      'Mavalor',
      'Mayuro',
      'Namuco',
      'Namunga',
      'Nasi',
      'Natu',
      'Palakpak',
      'Pinagsibaan',
      'Putingkahoy',
      'Quilib',
      'Salao',
      'San Carlos',
      'San Ignacio',
      'San Jose',
      'San Roque',
      'Santa Cruz',
      'Timbugan',
      'Tiquiwan',
      'Tulos',
    ],
  },
  {
    name: 'San Jose',
    type: 'municipality',
    coordinates: { latitude: 13.8833, longitude: 121.1167 },
    barangays: [
      'Aguila',
      'Anus',
      'Aya',
      'Bagong Pook',
      'Balagtasin',
      'Balagtasin I',
      'Banaybanay I',
      'Banaybanay II',
      'Bigain I',
      'Bigain II',
      'Bigain South',
      'Calansayan',
      'Dagatan',
      'Don Luis',
      'Galamay-Amo',
      'Lalayat',
      'Lapolapo I',
      'Lapolapo II',
      'Lepute',
      'Lumil',
      'Mojon-Tampoy',
      'Natunuan',
      'Palanca',
      'Poblacion Barangay I',
      'Poblacion Barangay II',
      'Poblacion Barangay III',
      'Poblacion Barangay IV',
      'Sabang',
      'Salaban',
      'Santo Cristo',
      'Taysan',
      'Tugtug',
    ],
  },
  {
    name: 'San Juan',
    type: 'municipality',
    coordinates: { latitude: 13.8167, longitude: 121.4 },
    barangays: [
      'Abung',
      'Balagbag',
      'Barualte',
      'Bataan',
      'Buhay Na Sapa',
      'Bulsa',
      'Calicanto',
      'Calitcalit',
      'Calubcub I',
      'Calubcub II',
      'Catmon',
      'Coloconto',
      'Escribano',
      'Hugom',
      'Imelda',
      'Janaojanao',
      'Laiya-Aplaya',
      'Laiya-Ibabao',
      'Libato',
      'Lipahan',
      'Mabalanoy',
      'Muzon',
      'Nagsaulay',
      'Palahanan I',
      'Palahanan II',
      'Palingowak',
      'Pinagbayanan',
      'Poblacion',
      'Poctol',
      'Pulangbato',
      'Putingbuhangin',
      'Quipot',
      'Sampiro',
      'Sapangan',
      'Sico I',
      'Sico II',
      'Subukin',
      'Talahiban I',
      'Talahiban II',
      'Tipaz',
    ],
  },
  {
    name: 'San Luis',
    type: 'municipality',
    coordinates: { latitude: 13.85, longitude: 121.3833 },
    barangays: [
      'Abiacao',
      'Bagong Tubig',
      'Balagtasin',
      'Balite',
      'Banoyo',
      'Boboy',
      'Bonliw',
      'Calumpang East',
      'Calumpang West',
      'Dulangan',
      'Durungao',
      'Locloc',
      'Luya',
      'Mahabang Parang',
      'Manggahan',
      'Muzon',
      'Poblacion',
      'San Antonio',
      'San Isidro',
      'San Jose',
      'San Martin',
      'Santa Monica',
      'Talon',
      'Tejero',
      'Tungal',
    ],
  },
  {
    name: 'San Nicolas',
    type: 'municipality',
    coordinates: { latitude: 13.9333, longitude: 120.95 },
    barangays: [
      'Abelo',
      'Alas-as',
      'Balete',
      'Baluk-baluk',
      'Bancoro',
      'Bangin',
      'Calangay',
      'Hipit',
      'Maabud North',
      'Maabud South',
      'Munlawin',
      'Pansipit',
      'Poblacion',
      'Pulang-Bato',
      'Santo Niño',
      'Sinturisan',
      'Tagudtod',
      'Talang',
    ],
  },
  {
    name: 'San Pascual',
    type: 'municipality',
    coordinates: { latitude: 13.8167, longitude: 121.0167 },
    barangays: [
      'Alalum',
      'Antipolo',
      'Balimbing',
      'Banaba',
      'Bayanan',
      'Danglayan',
      'Del Pilar',
      'Gelerang Kawayan',
      'Ilat North',
      'Ilat South',
      'Kaingin',
      'Laurel',
      'Malaking Pook',
      'Mataas Na Lupa',
      'Natunuan North',
      'Natunuan South',
      'Padre Castillo',
      'Palsahingin',
      'Pila',
      'Poblacion',
      'Pook Ni Banal',
      'Pook Ni Kapitan',
      'Resplandor',
      'Sambat',
      'San Antonio',
      'San Mateo',
      'Santa Elena',
      'Santo Niño',
    ],
  },
  {
    name: 'Santa Teresita',
    type: 'municipality',
    coordinates: { latitude: 13.8667, longitude: 121.2167 },
    barangays: [
      'Antipolo',
      'Bihis',
      'Burol',
      'Calayaan',
      'Calumala',
      'Cuta East',
      'Cutang Cawayan',
      'Irukan',
      'Pacifico',
      'Poblacion I',
      'Poblacion II',
      'Poblacion III',
      'Saimsim',
      'Sampa',
      'Sinipian',
      'Tambo Ibaba',
      'Tambo Ilaya',
    ],
  },
  {
    name: 'Santo Tomas City',
    type: 'city',
    coordinates: { latitude: 14.1078, longitude: 121.1414 },
    barangays: [
      'Barangay I (Pob.)',
      'Barangay II (Pob.)',
      'Barangay III (Pob.)',
      'Barangay IV (Pob.)',
      'San Agustin',
      'San Antonio',
      'San Bartolome',
      'San Felix',
      'San Fernando',
      'San Francisco',
      'San Isidro Norte',
      'San Isidro Sur',
      'San Joaquin',
      'San Jose',
      'San Juan',
      'San Luis',
      'San Miguel',
      'San Pablo',
      'San Pedro',
      'San Rafael',
      'San Roque',
      'San Vicente',
      'Santa Ana',
      'Santa Anastacia',
      'Santa Clara',
      'Santa Cruz',
      'Santa Elena',
      'Santa Teresita',
      'Santiago',
    ],
  },
  {
    name: 'Taal',
    type: 'municipality',
    coordinates: { latitude: 13.8833, longitude: 120.9167 },
    barangays: [
      'Apacay',
      'Balisong',
      'Bihis',
      'Bolbok',
      'Buli',
      'Butong',
      'Carasuche',
      'Cawit',
      'Caysasay',
      'Cubamba',
      'Cultihan',
      'Gahol',
      'Halang',
      'Iba',
      'Ilog',
      'Imamawo',
      'Ipil',
      'Laguile',
      'Latag',
      'Luntal',
      'Mahabang Lodlod',
      'Niogan',
      'Pansol',
      'Poblacion 1',
      'Poblacion 10',
      'Poblacion 11',
      'Poblacion 12',
      'Poblacion 13',
      'Poblacion 14',
      'Poblacion 2',
      'Poblacion 3',
      'Poblacion 4',
      'Poblacion 6',
      'Poblacion 7',
      'Poblacion 8',
      'Poblacion 9',
      'Pook',
      'Seiran',
      'Tatlong Maria',
      'Tierra Alta',
      'Tulo',
    ],
  },
  {
    name: 'Talisay',
    type: 'municipality',
    coordinates: { latitude: 14.1, longitude: 121.0167 },
    barangays: [
      'Aya',
      'Balas',
      'Banga',
      'Buco',
      'Caloocan',
      'Leynes',
      'Miranda',
      'Poblacion Barangay 1',
      'Poblacion Barangay 2',
      'Poblacion Barangay 3',
      'Poblacion Barangay 4',
      'Poblacion Barangay 5',
      'Poblacion Barangay 6',
      'Poblacion Barangay 7',
      'Poblacion Barangay 8',
      'Quiling',
      'Sampaloc',
      'San Guillermo',
      'Santa Maria',
      'Tranca',
      'Tumaway',
    ],
  },
  {
    name: 'Tanauan City',
    type: 'city',
    coordinates: { latitude: 14.0869, longitude: 121.1498 },
    barangays: [
      'Altura Bata',
      'Altura Matanda',
      'Altura-South',
      'Ambulong',
      'Bagbag',
      'Bagumbayan',
      'Balele',
      'Banadero',
      'Banjo East',
      'Banjo Laurel',
      'Bilog-bilog',
      'Boot',
      'Cale',
      'Darasa',
      'Gonzales',
      'Hidalgo',
      'Janopol',
      'Janopol Oriental',
      'Laurel',
      'Luyos',
      'Mabini',
      'Malaking Pulo',
      'Maria Paz',
      'Maugat',
      'Montaña',
      'Natatas',
      'Pagaspas',
      'Pantay Matanda',
      'Poblacion Barangay 1',
      'Poblacion Barangay 2',
      'Poblacion Barangay 3',
      'Poblacion Barangay 4',
      'Poblacion Barangay 5',
      'Poblacion Barangay 6',
      'Poblacion Barangay 7',
      'Sala',
      'Sambat',
      'Santol',
      'Santor',
      'Sulpoc',
      'Suplang',
      'Talaga',
      'Tinurik',
      'Trapiche',
      'Ulango',
      'Wawa',
    ],
  },
  {
    name: 'Taysan',
    type: 'municipality',
    coordinates: { latitude: 13.8667, longitude: 121.1 },
    barangays: [
      'Bacao',
      'Bilogo',
      'Bukal',
      'Dagatan',
      'Guinhawa',
      'Laurel',
      'Mabayabas',
      'Mahanadiong',
      'Mapulo',
      'Mataas Na Lupa',
      'Pag-Asa',
      'Panghayaan',
      'Pinagbayanan',
      'Piña',
      'Poblacion East',
      'Poblacion West',
      'San Isidro',
      'San Marcelino',
      'Santo Niño',
      'Tilambo',
    ],
  },
  {
    name: 'Tingloy',
    type: 'municipality',
    coordinates: { latitude: 13.6667, longitude: 120.8667 },
    barangays: [
      'Barangay 13',
      'Barangay 14',
      'Barangay 15',
      'Corona',
      'Gamao',
      'Makawayan',
      'Marikaban',
      'Papaya',
      'Pisa',
      'San Isidro',
      'San Jose',
      'San Juan',
      'San Pedro',
      'Santo Tomas',
      'Talahib',
    ],
  },
  {
    name: 'Tuy',
    type: 'municipality',
    coordinates: { latitude: 14.0167, longitude: 120.7333 },
    barangays: [
      'Acle',
      'Bayudbud',
      'Bolboc',
      'Burgos (Pob.)',
      'Dalima',
      'Dao',
      'Guinhawa',
      'Lumbangan',
      'Luna (Pob.)',
      'Luntal',
      'Magahis',
      'Malibu',
      'Mataywanac',
      'Palincaro',
      'Putol',
      'Rillo (Pob.)',
      'Rizal (Pob.)',
      'Sabang',
      'San Jose',
      'Talon',
      'Toong',
      'Tuyon-tuyon',
    ],
  },
];

export const BATANGAS_LOCATION_OPTIONS = BATANGAS_LOCATIONS.map((loc) => ({
  key: loc.name.toLowerCase().replace(/[^a-z0-9]+/g, '_'),
  label: loc.name,
  type: loc.type,
  coordinates: loc.coordinates,
  barangays: loc.barangays,
}));

export const getBatangasLocationByLabel = (label) => BATANGAS_LOCATION_OPTIONS.find((loc) => loc.label === label) || null;
